// Lifetime Care (senior + chronic condition) hub FAQ — Month 3 copy.
// `lifetimeCareFaqs` renders on the page; `lifetimeCareFaqSchema` is the verbatim
// FAQPage JSON-LD (condensed, third-person answers authored separately for schema).
// Every clinical figure below traces to the Month 3 clinical fact base: 2023 AAHA
// Senior Care Guidelines, AAHA Mobility Matters, IRIS CKD staging (modified 2019),
// 2016 AAFP Hyperthyroidism Guidelines, ACVIM MMVD consensus / EPIC, FDA and EMA
// labeling for bedinvetmab and frunevetmab, and Villalobos HHHHHMM.

import type { ServiceFaq } from "../services/fear-free/faq";

export const lifetimeCareFaqs: ServiceFaq[] = [
  {
    question: "At what age is a dog or cat considered senior?",
    answer:
      "There is no single birthday, and the common shorthand that dogs become senior at seven is wrong often enough to matter. AAHA defines senior by proportion of expected lifespan — the last 25% of it — which means size drives the answer in dogs. Small breeds often are not senior until around 12. Large breeds can reach senior status as early as 7 to 8 years, and giant breeds earlier still. Cats are simpler, because feline lifespan varies far less by breed: senior means over 10 years old, and cats aged 7 to 10 are classed as mature adults. Treat these as practical ranges rather than thresholds, and let us individualize it for your pet at the next exam.",
  },
  {
    question: "How often should a senior pet be examined, and what does senior screening include?",
    answer:
      "AAHA recommends senior dogs be examined at least twice a year, with the lab panel every 6 to 12 months. The minimum database is a complete blood count, a chemistry panel (total protein, albumin, ALT, glucose, BUN, creatinine, sodium, potassium, calcium, and SDMA where available), and a urinalysis. Thyroid testing and blood pressure are added annually, and both are strongly recommended annually in cats, with blood pressure every 6 to 12 months in healthy geriatric cats. Depending on what we find we add a urine protein:creatinine ratio, NT-proBNP, or an ECG in breeds at high cardiac risk such as Boxers and Dobermans. The urinalysis is not redundant with the bloodwork: urine specific gravity can show the kidneys losing concentrating ability before creatinine moves, and protein in urine flags damage a chemistry panel alone would miss.",
  },
  {
    question: "My older dog is slowing down. Is that arthritis or just age?",
    answer:
      "Slowing down is a description, not a diagnosis, and arthritis is the most common thing hiding behind it. Roughly one in five dogs is diagnosed with osteoarthritis in their lifetime, and that is a diagnosis rate rather than a true prevalence — the real number is higher, because owners read the signs as aging. Watch for the behavioral signs rather than an obvious limp: hesitating at stairs, lagging on the back half of a walk, difficulty rising after rest, no longer jumping onto the couch or into the car, restlessness or changed sleep, and new irritability when handled. Record a phone video of your dog moving at home and bring it. AAHA specifically endorses owner video, because a stressed dog on a slick exam-room floor hides exactly what we need to see. It is also worth ruling other things out, since night pacing can be pain, cognitive dysfunction, high blood pressure, or something else entirely.",
  },
  {
    question: "How would I know if my cat has arthritis? Cats do not limp.",
    answer:
      "They almost never do, and that is precisely the problem. More than 60% of cats have osteoarthritis in at least one joint. Feline arthritis is usually bilateral, so both sides hurt equally and there is nothing to favor, and cats rarely have the crepitus in affected joints that gives dogs away on a physical exam. In one radiographic study, owners had recognized lameness in only two cats, and no obvious pain was detected on palpation in any cat with limb arthritis. A separate retrospective radiographic study found degenerative joint disease in the limbs of 74% of 101 cats screened. What you will actually see is a cat who jumps less or jumps to a lower surface, has lost some fluidity in its gait, is less active especially at night, and newly objects to being picked up, petted, or having its back or hind legs stroked. Commonly affected joints are the hip, stifle, hock, elbow, and the spine.",
  },
  {
    question: "Are Librela and Solensia safe?",
    answer:
      "Both are anti-NGF monoclonal antibodies given as a monthly in-clinic injection, and both are legitimate, currently approved options we discuss case by case rather than recommend or reject on a web page. Solensia (frunevetmab) for cats was FDA-approved in January 2022, the first monoclonal antibody approved for any animal species; the most frequently reported adverse reactions in its studies were vomiting, diarrhea, dermatitis, and hair loss. Librela (bedinvetmab) for dogs was FDA-approved in May 2023 and remains approved and on the market with no recall. It also carries a real, actively evolving safety signal. In February 2025 the US label added a Post-Approval Experience section listing ataxia, seizures, other neurologic signs, urinary incontinence, increased thirst and urination, and death including euthanasia, and the label now expects your veterinarian to provide a client information sheet and discuss adverse events with you before administration. In March 2026 the European CVMP recommended adding very rare musculoskeletal adverse events to the product information, including very rare suspected cases of abnormal osteoarthritis progression. Adverse event reports are voluntary, unverified, and do not establish that a drug caused the event, and an elderly arthritic population gets sick for many reasons. What that adds up to is a real conversation before the first injection. If your dog is already on Librela, do not stop it because of something you read online — talk to us.",
  },
  {
    question: "What are the stages of kidney disease in cats?",
    answer:
      "Chronic kidney disease is staged 1 through 4 using the IRIS system, based on fasting creatinine and/or SDMA measured on at least two occasions in a hydrated, stable patient. One elevated value from a dehydrated cat is not a diagnosis. In cats, Stage 1 is creatinine under 1.6 mg/dL, Stage 2 is 1.6 to 2.8, Stage 3 is 2.9 to 5.0, and Stage 4 is above 5.0. Each stage is then sub-staged twice more, by urine protein:creatinine ratio and by blood pressure, because proteinuria and hypertension change what we do about it. SDMA earns its place on a senior panel because it rises earlier than creatinine and is less affected by lost muscle mass, which is the exact trap in a thin old cat. For perspective: in one study 80.9% of cats aged 15 to 20 had CKD, and among affected cats the great majority were Stage 1 or Stage 2. Most of what screening finds is early, which is the entire argument for screening rather than waiting for symptoms.",
  },
  {
    question: "What are the earliest signs of dog dementia, and how is it different from normal aging?",
    answer:
      "The clinical framework is DISHAA: Disorientation, altered social Interactions, disrupted Sleep-wake cycles, loss of House training and other learned behaviors, changed Activity levels, and increased Anxiety. In dogs it usually starts as sleeping through the day and becoming restless at night, less interaction with the family, getting lost or stuck in familiar rooms, and new anxiety. Cats tend the other way, toward more vocalizing and more clinging. Roughly 14 to 22.5% of dogs over eight have age-related cognitive impairment, but only about 1.9% are diagnosed, because owners file the changes under old age and never mention them. Cognitive dysfunction is also a diagnosis of exclusion, and the bloodwork is the point rather than a formality: night pacing may be arthritis pain, house-soiling may be a urinary tract infection or kidney disease or diabetes, and disorientation may be high blood pressure or an intracranial tumor. Selegiline is the only FDA-approved drug for canine cognitive dysfunction, with improvement reported in up to 70% of dogs, and it is combined with enrichment, dietary support, and anxiety medication where anxiety is a real component. It slows and softens the condition. It does not reverse it.",
  },
  {
    question: "Is my pet too old for anesthesia or a dental cleaning?",
    answer:
      "Age by itself is not a disease and is not a contraindication. AAHA states that advanced age does not preclude surgery or other significant medical intervention, and that senior pets can safely undergo multiple anesthetic events. What determines risk is organ function, cardiac and respiratory reserve, and concurrent disease, which is why the answer starts with pre-anesthetic bloodwork and NT-proBNP strongly considered before an anesthetic event, rather than with a birthday. For senior patients we use tailored induction, preoxygenation where there is cardiac or pulmonary disease, active warming, padded positioning, minimized anesthesia time, and longer recovery monitoring. The honest counterweight to 'she is too old for a dental' is usually that she has been in chronic oral pain for two years. Our dental page covers the anesthesia protocol in detail, and our standard dental is $999 with extractions quoted separately. One real limit: if a senior patient would need overnight intravenous care after a procedure, that is a planned transfer to a 24-hour hospital, because we have no overnight staff.",
  },
  {
    question: "What is a quality-of-life scale and how do I score my own pet honestly?",
    answer:
      "The most widely used is the HHHHHMM scale developed by Dr. Alice Villalobos, which scores seven domains from 0 to 10 for a total out of 70: Hurt (pain control and the ability to breathe), Hunger, Hydration, Hygiene, Happiness, Mobility, and More good days than bad. Roughly 35 is the reference point — consistently above it generally means quality of life remains acceptable and supportive care can continue, and a total that stays below it is the signal to have a fuller conversation. Two cautions we would rather state than skip. AAHA notes that very few quality-of-life scales for animals are validated and that most found online are not; HHHHHMM has had one partial validation in a narrow sample, so it is a structured framework, not a diagnostic instrument. And a score is not an instruction to do anything. Its real value is that it makes you look at seven specific things instead of drowning in one enormous feeling. Marking good days and bad days on a calendar works nearly as well and costs nothing.",
  },
  {
    question: "How do I know when it is time to euthanize my dog or cat?",
    answer:
      "No web page can answer that for your animal, and any page that tries is selling you a certainty it does not have. What we can do is name the moments AAHA lists as the ones that should trigger the conversation: not eating, symptoms progressing, severe or unrelenting chronic pain, deterioration during active treatment, a persistent cough even at rest, cognitive dysfunction that keeps advancing, and mobility that has failed. Bring those to us and we will work through it properly — your understanding of where things stand, a full exam with a pain assessment, an honest prognosis, your goals rather than ours, and only then the options: continued treatment, symptom and pain management with us, referral to a hospice or mobile end-of-life provider, or humane euthanasia. We are not a hospice service and we do not visit homes, so where a family wants dedicated hospice support or care at home we will point you to a provider who does that. Tell us when you book that this is what the visit is about. We will also talk through the setting in advance if you want to. One thing we have to say plainly: we are open Monday through Friday, 8 a.m. to 5 p.m., with no overnight staff and no after-hours on-call line. If your pet is suffering on a Saturday night, an emergency hospital can provide humane euthanasia that night, and mobile end-of-life veterinarians serve Colorado Springs. Waiting until Monday because you would rather it be us is not the kind choice.",
  },
];

// Verbatim FAQPage JSON-LD (condensed, third-person answers authored for schema).
export const lifetimeCareFaqSchema = `{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {"@type":"Question","name":"At what age is a dog or cat considered senior?","acceptedAnswer":{"@type":"Answer","text":"There is no single age. AAHA defines senior by proportion of expected lifespan, the last 25% of it, so size drives the answer in dogs: small breeds often are not senior until around 12, large breeds can reach senior status as early as 7 to 8 years, and giant breeds earlier still. Cats are simpler because feline lifespan varies far less by breed: senior means over 10 years old, and cats aged 7 to 10 are mature adults. The common shorthand that dogs are senior at seven is not supported by AAHA."}},
    {"@type":"Question","name":"How often should a senior dog or cat be examined, and what does senior screening include?","acceptedAnswer":{"@type":"Answer","text":"AAHA recommends senior dogs be examined at least twice a year, with a lab panel every 6 to 12 months. The minimum database is a complete blood count, a chemistry panel including total protein, albumin, ALT, glucose, BUN, creatinine, sodium, potassium, calcium and SDMA where available, plus a urinalysis. Thyroid testing and blood pressure are added annually and are strongly recommended annually in cats, with blood pressure every 6 to 12 months in healthy geriatric cats. Urine protein:creatinine ratio, NT-proBNP, and ECG in high cardiac risk breeds are added based on findings."}},
    {"@type":"Question","name":"Is my older dog slowing down because of arthritis or just age?","acceptedAnswer":{"@type":"Answer","text":"Arthritis is the most common cause of a senior dog slowing down. Roughly one in five dogs is diagnosed with osteoarthritis in their lifetime, and that is a diagnosis rate rather than a true prevalence. The early signs are behavioral rather than an obvious limp: hesitating at stairs, lagging on walks, difficulty rising after rest, no longer jumping onto furniture or into the car, restlessness or changed sleep, and new irritability when handled. AAHA endorses bringing a phone video of the dog moving at home, because a stressed dog on a slick exam-room floor hides the signs. Night pacing can also be cognitive dysfunction or high blood pressure, so an exam is needed to tell them apart."}},
    {"@type":"Question","name":"How can I tell if my cat has arthritis if cats do not limp?","acceptedAnswer":{"@type":"Answer","text":"More than 60% of cats have osteoarthritis in at least one joint, and cats almost never limp because feline arthritis is usually bilateral, so both sides hurt equally. Cats also rarely have crepitus in affected joints, the finding that reveals arthritis in dogs on physical exam. In one radiographic study, owners recognized lameness in only two cats, and no obvious pain was detected on palpation in any cat with limb arthritis. What owners actually see is a cat jumping less or to a lower surface, a stiffer and less fluid gait, less activity especially at night, and new resistance to being picked up, petted, or having the back or hind legs stroked. Commonly affected joints are the hip, stifle, hock, elbow and spine."}},
    {"@type":"Question","name":"Are Librela and Solensia safe for arthritis pain in dogs and cats?","acceptedAnswer":{"@type":"Answer","text":"Both are anti-NGF monoclonal antibodies given as a monthly in-clinic injection. Solensia (frunevetmab) for cats was FDA-approved in January 2022, the first monoclonal antibody approved for any animal species, with vomiting, diarrhea, dermatitis and hair loss the most frequently reported adverse reactions in studies. Librela (bedinvetmab) for dogs was FDA-approved in May 2023 and remains approved with no recall, but carries an evolving safety signal: the February 2025 US label update added a Post-Approval Experience section listing ataxia, seizures, other neurologic signs, urinary incontinence, increased thirst and urination, and death including euthanasia, and expects the veterinarian to provide a client information sheet and discuss adverse events before administration. In March 2026 the EMA CVMP recommended adding very rare musculoskeletal adverse events to the product information. Adverse event reports are voluntary and unverified and do not establish causation. The correct step is a conversation with your veterinarian, not a decision made from a website."}},
    {"@type":"Question","name":"What are the stages of chronic kidney disease in cats?","acceptedAnswer":{"@type":"Answer","text":"Chronic kidney disease is staged 1 through 4 using the IRIS system, based on fasting creatinine and/or SDMA measured on at least two occasions in a hydrated, stable patient. In cats, Stage 1 is creatinine under 1.6 mg/dL, Stage 2 is 1.6 to 2.8, Stage 3 is 2.9 to 5.0, and Stage 4 is above 5.0. Each stage is sub-staged twice more, by urine protein:creatinine ratio and by blood pressure. SDMA rises earlier than creatinine and is less affected by lost muscle mass, which matters in thin senior cats. In one study 80.9% of cats aged 15 to 20 had CKD, and the great majority of affected cats were Stage 1 or Stage 2."}},
    {"@type":"Question","name":"What are the earliest signs of dog dementia or canine cognitive dysfunction?","acceptedAnswer":{"@type":"Answer","text":"The clinical framework is DISHAA: Disorientation, altered social Interactions, disrupted Sleep-wake cycles, loss of House training and other learned behaviors, changed Activity levels, and increased Anxiety. Dogs typically sleep through the day and become restless at night, interact less, get lost in familiar rooms, and develop new anxiety; cats tend toward more vocalizing and more clinging. Roughly 14 to 22.5% of dogs over eight have age-related cognitive impairment but only about 1.9% are diagnosed. Cognitive dysfunction is a diagnosis of exclusion, because night pacing may be arthritis pain and house-soiling may be a urinary tract infection, kidney disease or diabetes. Selegiline is the only FDA-approved drug for canine cognitive dysfunction, with improvement reported in up to 70% of dogs. It slows and softens the condition rather than reversing it."}},
    {"@type":"Question","name":"Is my pet too old for anesthesia or a dental cleaning?","acceptedAnswer":{"@type":"Answer","text":"Age by itself is not a disease. AAHA states that advanced age does not preclude surgery or other significant medical intervention and that senior pets can safely undergo multiple anesthetic events. Risk is determined by organ function, cardiac and respiratory reserve and concurrent disease, so the assessment starts with pre-anesthetic bloodwork and NT-proBNP strongly considered before an anesthetic event. Senior protocols at Red Rock Veterinary Health use tailored induction, preoxygenation where indicated, active warming, padded positioning, minimized anesthesia time and longer recovery monitoring. A standard dental is $999, with extractions quoted separately. If a senior patient would need overnight intravenous care after a procedure, that is a planned transfer to a 24-hour hospital, because Red Rock has no overnight staff."}},
    {"@type":"Question","name":"What is a pet quality of life scale and how do I use it?","acceptedAnswer":{"@type":"Answer","text":"The most widely used is the HHHHHMM scale developed by Dr. Alice Villalobos, scoring seven domains from 0 to 10 for a total out of 70: Hurt, meaning pain control and the ability to breathe, plus Hunger, Hydration, Hygiene, Happiness, Mobility, and More good days than bad. Roughly 35 is the reference point. AAHA notes that very few quality-of-life scales for animals are validated and most found online are not, and HHHHHMM has had only one partial validation in a narrow sample, so it is a structured framework rather than a diagnostic instrument. A score is not an instruction. Its value is that it directs attention to seven specific things. Marking good and bad days on a calendar works nearly as well."}},
    {"@type":"Question","name":"How do I know when it is time to euthanize my dog or cat?","acceptedAnswer":{"@type":"Answer","text":"No website can answer that for an individual animal. AAHA names the scenarios that should trigger the conversation: not eating, symptom progression, severe or unrelenting chronic pain, deterioration during active treatment, a persistent cough even at rest, progressing cognitive dysfunction, and mobility issues. The conversation at Red Rock Veterinary Health starts with the owner's understanding of the situation, then a full exam with pain assessment, an honest prognosis, the owner's goals of care, and only then the options: continued treatment, symptom and pain management at Red Rock, referral to a hospice or mobile end-of-life provider, or humane euthanasia. Red Rock is a general practice rather than a hospice service and does not make home visits. Red Rock is open Monday through Friday, 8 a.m. to 5 p.m., with no overnight staff and no after-hours on-call line. A pet suffering outside those hours should be seen by an emergency hospital, which can provide humane euthanasia that night; mobile end-of-life veterinarians also serve Colorado Springs."}}
  ]
}`;
